import type { Mood } from './engine/model'

/** [person, mood, calls, reason, what Jade did, needs action today, booked / review on] */
export type CallerRow = [string, Mood, number, string, string, 0 | 1, string]
export type CallerGroup = [string, string, CallerRow[]]

/** Hand-checked summary of every caller, from the prototype. */
export const EVERY_CALLER: CallerGroup[] = [
  [
    'r',
    'Urgent',
    [
      [
        'Peter Young',
        'nicer',
        1,
        'Urgent call at 2:14am',
        'Advised emergency department if genuine emergency, took details, flagged for Monday',
        1,
        'Review Mon 17 Nov, first thing',
      ],
      [
        'Michael Brown',
        'nicer',
        2,
        'Billing dispute (complaint)',
        'Took a message both times. No callback since Friday evening.',
        1,
        'Review Mon 17 Nov, today',
      ],
    ],
  ],
  [
    'o',
    'Needs a callback or action',
    [
      [
        'Grace Scott',
        'nicer',
        2,
        'New patient, wants a slot before month end',
        'Nothing available twice, took details for the waitlist',
        0,
        'Review Mon 17 Nov',
      ],
      [
        'David Miller',
        'nicer',
        1,
        'New patient, wanted a slot this week',
        'Nothing available. He said he would try somewhere else.',
        0,
        'Review Mon 17 Nov',
      ],
      [
        'Rachel Lewis',
        'nicer',
        1,
        'Cancelled Tue 11:00 (family emergency)',
        'Cancelled it, noted she wants a call to rebook',
        0,
        'Cancelled Tue 18 Nov 11:00. Low-priority rebook call Mon 24 Nov',
      ],
      [
        'Natalie Evans',
        'normal',
        1,
        'Cancelled Thu 14:00 (travelling)',
        'Cancelled it, she will call back to rebook',
        0,
        'Cancelled Thu 20 Nov 14:00. Low-priority rebook call Mon 17 Nov',
      ],
      [
        'Daniel Clark',
        'normal',
        1,
        'Asked about orthodontics (not offered)',
        'Took a message, said the practice will call with a referral',
        0,
        'Low priority, after 14:00 Mon 17 Nov',
      ],
      [
        'James Anderson',
        'normal',
        1,
        'New patient wanting a first booking',
        'Captured a number one digit short, call dropped before confirming',
        0,
        'Review Mon 17 Nov',
      ],
    ],
  ],
  [
    'g',
    'Booked or rescheduled',
    [
      [
        'John Smith',
        'casual',
        1,
        'New patient, check-up and clean',
        'Booked with Dr Foster',
        0,
        'Booked Wed 19 Nov, 14:30',
      ],
      [
        'Sarah Johnson',
        'casual',
        2,
        'Cancelled, then rebooked',
        'Cancelled Mon 17 Nov 9:00 on Friday. Rebooked on Monday.',
        0,
        'Booked Thu 27 Nov, 9:00',
      ],
      [
        'Emily Davis',
        'casual',
        1,
        'New patient, wants a regular dentist',
        'Booked with Dr Bennett',
        0,
        'Booked Thu 20 Nov, 10:00',
      ],
      [
        'Jessica Wilson',
        'casual',
        1,
        'Existing patient, bring check-up forward',
        'Booked with Dr Foster',
        0,
        'Booked Fri 21 Nov, 16:00',
      ],
      [
        'Laura Thomas',
        'casual',
        1,
        "New patient, children's check-up (her son)",
        'Booked with Dr Bennett',
        0,
        'Booked Sat 22 Nov, 9:30 ⚠ closed day, final pass suggests two alternatives',
      ],
      [
        'Chris Martin',
        'nicer',
        3,
        'New patient, wanted Monday or Tuesday',
        'Nothing available twice, booked on the third call with Dr Foster',
        0,
        'Booked Thu 20 Nov, 15:30',
      ],
      [
        'Emma Hall',
        'casual',
        1,
        'Existing patient, routine clean',
        'Booked with Dr Bennett',
        0,
        'Booked Tue 25 Nov, 8:30',
      ],
      [
        'Olivia King',
        'casual',
        1,
        'New patient by referral, check-up and whitening',
        'Booked with Dr Foster',
        0,
        'Booked Mon 24 Nov, 11:00',
      ],
      [
        'Sophie Wright',
        'nicer',
        1,
        'New patient, note for practitioner',
        'Booked with Dr Bennett and passed the note on',
        0,
        'Booked Wed 26 Nov, 13:00. Chart note Mon 17 Nov',
      ],
      [
        'Andrew Green',
        'casual',
        1,
        'Existing patient, reschedule',
        "Moved to Dr Foster's Friday slot",
        0,
        'Booked Fri 21 Nov, 10:30',
      ],
      [
        'Hannah Moore',
        'casual',
        1,
        'Existing patient, routine booking',
        'Booked with Dr Bennett',
        0,
        'Booked Tue 2 Dec, 17:00 ⚠ closing time, low-priority fix',
      ],
      [
        'Kevin Turner',
        'normal',
        1,
        'New patient, weekend issue',
        'Booked an assessment with Dr Foster and flagged it priority. The final pass removed the flag.',
        0,
        'Booked Tue 18 Nov, 8:00',
      ],
    ],
  ],
  [
    'b',
    'Question answered',
    [
      [
        'Amanda Taylor',
        'casual',
        1,
        'Parking',
        'Confirmed street parking and the car park two doors down',
        0,
        '',
      ],
      [
        'Matthew Walker',
        'casual',
        1,
        'Does the clinic accept HCF?',
        'Confirmed yes, HICAPS available on site',
        0,
        '',
      ],
      [
        'Ryan Baker',
        'casual',
        1,
        'Gap fee for a check-up with HCF',
        'Gave the standard fee, explained the gap depends on cover',
        0,
        '',
      ],
    ],
  ],
  [
    'n',
    'No useful information',
    [
      [
        'Unknown caller',
        'normal',
        1,
        'Unknown',
        'Caller hung up during the greeting, nothing captured',
        0,
        '',
      ],
      [
        'Unknown caller',
        'normal',
        1,
        'Unknown',
        'Caller hung up during the greeting, nothing captured',
        0,
        '',
      ],
      [
        'Unknown caller',
        'normal',
        1,
        'Wrong number (looking for a vet)',
        'Identified the wrong number, no action',
        0,
        '',
      ],
    ],
  ],
]
